-- =============================================================================
-- Flink SQL: Shopify Orders Raw Ingestion
-- =============================================================================
-- Streams Shopify order events from Redpanda to Iceberg raw table.
-- This is an append-only streaming job that runs continuously.
--
-- Prerequisites:
--   - Run raw_ingestion_setup.sql first
--   - Redpanda topic 'shopify.orders' must exist
--   - Iceberg raw.shopify_orders table must exist
-- =============================================================================

-- Use the Iceberg catalog
USE CATALOG iceberg_catalog;
USE raw;

-- -----------------------------------------------------------------------------
-- Create Kafka Source Table
-- -----------------------------------------------------------------------------
-- Temporary table that reads from Redpanda
CREATE TEMPORARY TABLE shopify_orders_source (
    `id`                              BIGINT,
    `admin_graphql_api_id`            STRING,
    `order_number`                    BIGINT,
    `number`                          BIGINT,
    `name`                            STRING,
    `token`                           STRING,
    `confirmation_number`             STRING,
    `email`                           STRING,
    `phone`                           STRING,
    `customer`                        STRING,
    `billing_address`                 STRING,
    `shipping_address`                STRING,
    `currency`                        STRING,
    `presentment_currency`            STRING,
    `subtotal_price`                  STRING,
    `total_line_items_price`          STRING,
    `total_discounts`                 STRING,
    `total_price`                     STRING,
    `total_tax`                       STRING,
    `total_tip_received`              STRING,
    `total_outstanding`               STRING,
    `current_subtotal_price`          STRING,
    `current_total_price`             STRING,
    `current_total_discounts`         STRING,
    `current_total_tax`               STRING,
    `taxes_included`                  BOOLEAN,
    `estimated_taxes`                 BOOLEAN,
    `tax_exempt`                      BOOLEAN,
    `financial_status`                STRING,
    `fulfillment_status`              STRING,
    `cancel_reason`                   STRING,
    `cancelled_at`                    STRING,
    `closed_at`                       STRING,
    `confirmed`                       BOOLEAN,
    `line_items`                      STRING,
    `fulfillments`                    STRING,
    `refunds`                         STRING,
    `shipping_lines`                  STRING,
    `total_shipping_price_set`        STRING,
    `discount_codes`                  STRING,
    `tax_lines`                       STRING,
    `buyer_accepts_marketing`         BOOLEAN,
    `landing_site`                    STRING,
    `landing_site_ref`                STRING,
    `referring_site`                  STRING,
    `source_name`                     STRING,
    `source_identifier`               STRING,
    `source_url`                      STRING,
    `cart_token`                      STRING,
    `checkout_id`                     BIGINT,
    `checkout_token`                  STRING,
    `app_id`                          BIGINT,
    `browser_ip`                      STRING,
    `customer_locale`                 STRING,
    `note`                            STRING,
    `note_attributes`                 STRING,
    `order_status_url`                STRING,
    `payment_gateway_names`           STRING,
    `tags`                            STRING,
    `test`                            BOOLEAN,
    `total_weight`                    BIGINT,
    `user_id`                         BIGINT,
    `created_at`                      STRING,
    `updated_at`                      STRING,
    `processed_at`                    STRING,
    `_webhook_received_at`            STRING,
    `_webhook_topic`                  STRING,
    `_source`                         STRING,
    `_event_type`                     STRING,
    -- Kafka metadata
    `event_time` TIMESTAMP(3) METADATA FROM 'timestamp',
    WATERMARK FOR event_time AS event_time - INTERVAL '5' SECOND
) WITH (
    'connector' = 'kafka',
    'topic' = 'shopify.orders',
    'properties.bootstrap.servers' = 'redpanda:9092',
    'properties.group.id' = 'flink-shopify-orders-raw',
    'scan.startup.mode' = 'earliest-offset',
    'format' = 'json',
    'json.fail-on-missing-field' = 'false',
    'json.ignore-parse-errors' = 'true'
);

-- -----------------------------------------------------------------------------
-- Create Iceberg Sink Table (if not exists)
-- -----------------------------------------------------------------------------
-- Note: This matches the DDL in sql/00_raw/shopify/orders.sql
CREATE TABLE IF NOT EXISTS shopify_orders (
    `id`                              BIGINT,
    `admin_graphql_api_id`            STRING,
    `order_number`                    BIGINT,
    `number`                          BIGINT,
    `name`                            STRING,
    `token`                           STRING,
    `confirmation_number`             STRING,
    `customer_id`                     BIGINT,
    `email`                           STRING,
    `phone`                           STRING,
    `customer`                        STRING,
    `billing_address`                 STRING,
    `shipping_address`                STRING,
    `currency`                        STRING,
    `presentment_currency`            STRING,
    `subtotal_price`                  DECIMAL(18, 2),
    `total_line_items_price`          DECIMAL(18, 2),
    `total_discounts`                 DECIMAL(18, 2),
    `total_price`                     DECIMAL(18, 2),
    `total_tax`                       DECIMAL(18, 2),
    `total_tip_received`              DECIMAL(18, 2),
    `total_outstanding`               DECIMAL(18, 2),
    `current_subtotal_price`          DECIMAL(18, 2),
    `current_total_price`             DECIMAL(18, 2),
    `current_total_discounts`         DECIMAL(18, 2),
    `current_total_tax`               DECIMAL(18, 2),
    `taxes_included`                  BOOLEAN,
    `estimated_taxes`                 BOOLEAN,
    `tax_exempt`                      BOOLEAN,
    `financial_status`                STRING,
    `fulfillment_status`              STRING,
    `cancel_reason`                   STRING,
    `cancelled_at`                    TIMESTAMP(3),
    `closed_at`                       TIMESTAMP(3),
    `confirmed`                       BOOLEAN,
    `line_items`                      STRING,
    `fulfillments`                    STRING,
    `refunds`                         STRING,
    `shipping_lines`                  STRING,
    `total_shipping_price_set`        STRING,
    `discount_codes`                  STRING,
    `tax_lines`                       STRING,
    `buyer_accepts_marketing`         BOOLEAN,
    `landing_site`                    STRING,
    `landing_site_ref`                STRING,
    `referring_site`                  STRING,
    `source_name`                     STRING,
    `source_identifier`               STRING,
    `source_url`                      STRING,
    `cart_token`                      STRING,
    `checkout_id`                     BIGINT,
    `checkout_token`                  STRING,
    `app_id`                          BIGINT,
    `browser_ip`                      STRING,
    `customer_locale`                 STRING,
    `note`                            STRING,
    `note_attributes`                 STRING,
    `order_status_url`                STRING,
    `payment_gateway_names`           STRING,
    `tags`                            STRING,
    `test`                            BOOLEAN,
    `total_weight`                    BIGINT,
    `user_id`                         BIGINT,
    `created_at`                      TIMESTAMP(3),
    `updated_at`                      TIMESTAMP(3),
    `processed_at`                    TIMESTAMP(3),
    `_webhook_received_at`            TIMESTAMP(3),
    `_webhook_topic`                  STRING,
    `_loaded_at`                      TIMESTAMP(3)
) PARTITIONED BY (months(`created_at`))
WITH (
    'format-version' = '2',
    'write.upsert.enabled' = 'false'
);

-- -----------------------------------------------------------------------------
-- Streaming Insert Job
-- -----------------------------------------------------------------------------
INSERT INTO shopify_orders
SELECT
    `id`,
    `admin_graphql_api_id`,
    `order_number`,
    `number`,
    `name`,
    `token`,
    `confirmation_number`,
    -- Extract customer_id from nested JSON
    CAST(JSON_VALUE(customer, '$.id') AS BIGINT) as customer_id,
    `email`,
    `phone`,
    `customer`,
    `billing_address`,
    `shipping_address`,
    `currency`,
    `presentment_currency`,
    CAST(`subtotal_price` AS DECIMAL(18, 2)),
    CAST(`total_line_items_price` AS DECIMAL(18, 2)),
    CAST(`total_discounts` AS DECIMAL(18, 2)),
    CAST(`total_price` AS DECIMAL(18, 2)),
    CAST(`total_tax` AS DECIMAL(18, 2)),
    CAST(`total_tip_received` AS DECIMAL(18, 2)),
    CAST(`total_outstanding` AS DECIMAL(18, 2)),
    CAST(`current_subtotal_price` AS DECIMAL(18, 2)),
    CAST(`current_total_price` AS DECIMAL(18, 2)),
    CAST(`current_total_discounts` AS DECIMAL(18, 2)),
    CAST(`current_total_tax` AS DECIMAL(18, 2)),
    `taxes_included`,
    `estimated_taxes`,
    `tax_exempt`,
    `financial_status`,
    `fulfillment_status`,
    `cancel_reason`,
    TO_TIMESTAMP(`cancelled_at`),
    TO_TIMESTAMP(`closed_at`),
    `confirmed`,
    `line_items`,
    `fulfillments`,
    `refunds`,
    `shipping_lines`,
    `total_shipping_price_set`,
    `discount_codes`,
    `tax_lines`,
    `buyer_accepts_marketing`,
    `landing_site`,
    `landing_site_ref`,
    `referring_site`,
    `source_name`,
    `source_identifier`,
    `source_url`,
    `cart_token`,
    `checkout_id`,
    `checkout_token`,
    `app_id`,
    `browser_ip`,
    `customer_locale`,
    `note`,
    `note_attributes`,
    `order_status_url`,
    `payment_gateway_names`,
    `tags`,
    `test`,
    `total_weight`,
    `user_id`,
    TO_TIMESTAMP(`created_at`),
    TO_TIMESTAMP(`updated_at`),
    TO_TIMESTAMP(`processed_at`),
    TO_TIMESTAMP(`_webhook_received_at`),
    `_webhook_topic`,
    CURRENT_TIMESTAMP as `_loaded_at`
FROM shopify_orders_source;
